name: pauldd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ce2928'
    - '#121627'
    - '#3fbfe5'
    - '#b4cc52'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
