name: pauldd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.038399502635002136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fb2ec0'
    - '#ffffff'
    - '#38fefe'
    - '#e1c310'
  brandStrength: 0.6509403074160218
  lightness: 0.636246929410845
  saturation: 0.2996812278870493
  rhythmicContrast: 0.9990394096821547
purpose: []
